name: PR Checks (Basic Checks and Runner)

on:
  workflow_dispatch:

jobs:
  runner-analyze-csharp-autobuild-macos:
    name: Runner macos autobuild C# analyze
    runs-on: macos-latest

    env:
      ACTIONS_RUNNER_DEBUG: 1
    steps:
      - uses: actions/checkout@v2

      - name: Move codeql-action
        shell: bash
        run: |
          mkdir ../action
          mv * .github ../action/
          mv ../action/tests/multi-language-repo/{*,.github} .
          mv ../action/.github/workflows .github

      - name: Build runner
        run: |
          cd ../action/runner
          npm install
          npm run build-runner

      - name: Initialize dotnet
        run: dotnet restore

      - name: Run init
        run: |
          ../action/runner/dist/codeql-runner-macos init --repository $GITHUB_REPOSITORY --languages csharp --github-url $GITHUB_SERVER_URL --github-auth ${{ github.token }}

      - name: Create extractor directory
        run: |
          mkdir -p /Users/runner/work/codeql-action/codeql-action/codeql-runner/codeql_databases/csharp/log
          echo ""

      - name: Check env
        run: env

      - name: Build code
        shell: bash
        run: |
          export CODEQL_EXTRACTOR_CSHARP_LOG_DIR="/Users/runner/work/codeql-action/codeql-action/codeql-runner/codeql_databases/csharp/log"
          mkdir -p "$CODEQL_EXTRACTOR_CSHARP_LOG_DIR"
          touch "$CODEQL_EXTRACTOR_CSHARP_LOG_DIR/csharp.log"
          ../action/runner/dist/codeql-runner-macos autobuild

      - name: Check env
        if: always()
        run: env

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: /Users/runner/work/codeql-action/codeql-action/codeql-runner/codeql_databases/csharp

      - name: Run analyze
        run: |
          ../action/runner/dist/codeql-runner-macos analyze --repository $GITHUB_REPOSITORY --commit $GITHUB_SHA --ref $GITHUB_REF --github-url $GITHUB_SERVER_URL --github-auth ${{ github.token }}
        env:
          TEST_MODE: true

  
